---
title: "ATUS Clustering"
author: "Joe Marlo"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(mclust)
library(NbClust)
set.seed(44)
theme_set(theme_minimal())

atus_long <- read_tsv('Data/atus.tsv')
demographics <- read_tsv('Data/demographic.tsv')
```


# EDA

Only contains weekend only

```{r}
# description of the data
atus_long %>% 
  group_by(description) %>% 
  summarize(Mean = mean(value),
            part_rate = mean(value > 0)) %>% 
  arrange(desc(Mean)) %>% 
  mutate(Type = 'Continuous') %>% 
  janitor::adorn_totals() %>% 
  mutate(Mean = round(Mean, 0),
         part_rate = round(part_rate, 2),
         part_rate = ifelse(part_rate == 6.34, '-', part_rate)) %>% 
  select(Activity = description, Type, Mean, 'Participation rate' = part_rate) %>% 
  pander::pander(justify = c("left", "left", 'right', 'right'))
```

```{r}
# demographic data
map_dfr(demographics, table)
demographics %>% select_if(is.numeric) %>% purrr::map_dfc(max) %>% rbind() %>% enframe() %>% unlist()
purrr::map(demographics, table)
 map(demographics, function(x) table(x))

demographics %>% 
  pivot_longer(cols = -ID)
```


